version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/Season-2/Level-4"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gomod"
    directory: "/Season-2/Level-2"
    schedule:
      interval: "weekly"
